<?php
/**
 * Created by JetBrains PhpStorm.
 * User: admin
 * Date: 6/8/16
 * Time: 9:39 PM
 * To change this template use File | Settings | File Templates.
 */
/**
 * Implement hook_entity
 */

function staff_entity_info()
{
  return array(
    'staff' => array(
      "label" => "Staff",
      "base table" => "staff",
      'controller class' => 'StaffController',
      "fieldable" => false,
      'entity keys' => array(
        'id' => 'id',
      ),
      'views controller class' => 'StaffViewsController',
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => TRUE
        )
      )
    )
  );
}


/**
 * Implements hook_menu().
 * Add menu for order
 */
function staff_menu()
{
  $item = array();
  $item['staff/add'] = array(
    'title' => t('Thêm nhân viên'),
    'access arguments' => array('staff:*:add'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('staff_add_form', 2),
    'file' => 'includes/staff.page.inc',
    'type' => MENU_LOCAL_ACTION
  );
  $item['staff/edit/%staff'] = array(
    'title' => t('Cập nhật nhân viên'),
    'access arguments' => array('staff:*:edit'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('staff_add_form', 2),
    'file' => 'includes/staff.page.inc',
    'type' => MENU_LOCAL_ACTION
  );

  $item['staff/delete/%staff'] = array(
    'title' => t('Xóa nhân viên'),
    'access arguments' => array('staff:*:delete'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('staff_delete_form', 2),
    'file' => 'includes/staff.page.inc',
    'type' => MENU_LOCAL_ACTION
  );
  return $item;
}

/**
 * Implement hook_views_api
 * @return array
 */
function staff_views_api()
{
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'staff') . '/includes/views',
  );
}

/**
 * @param $id
 * @return mixedImplement hook_entity_load
 * Order_load
 */
function staff_load($id)
{
  $entity = staff_load_multiple(array($id));
  return reset($entity);
}

/**
 * Implements cook table Load Multiple
 * @Param $ids = array();
 */
function staff_load_multiple($ids)
{
  return entity_load('staff', $ids);
}

/**
 * Implements cook table Create
 */
function staff_create($entity)
{
  return entity_save('staff', $entity);
}

/**
 * Implements cook table Cupdate
 */
function staff_save($entity)
{
  return entity_save('staff', $entity);
}

/**
 * @param $ids
 * @param $conditions
 * @return mixed
 * Implements load cook table with condition
 */
function staff_load_multiple_with_conditions($ids, $conditions)
{
  return entity_load('staff', $ids, $conditions);
}

/**
 * Implements order delete
 */
function staff_delete($id)
{
  return entity_delete('staff', $id);
}

/**
 * Implements hook_permission().
 */
function staff_permission()
{
  return array(
    'staff:*:add' => array(
      'title' => t('Thêm nhân viên'),
    ),
    'staff:*:edit' => array(
      'title' => t('Cập nhật nhân viên'),
    ),
    'staff:*:delete' => array(
      'title' => t('Xóa nhân viên'),
    ),
  );
}

/**
 * Implement check exit cook table
 */
function staff_get_staff($field, $value)
{
  $query = db_select('staff', 'd');
  $query->fields('d');
  $query->condition($field, $value, '=');
  $result = $query->execute()->fetchAll();
  if ($result) {
    return $result;
  } else {
    return false;
  }
}

/**
 * Implement hook_page_alter
 */
function staff_page_alter(&$page){
  if($_GET['q']=='app/staff/manager'){
    $page['content']['add_staff'] = array(
      '#weight' => 100,
      '#markup' => ' <ul class="action-links"><li><a href="/staff/add">Thêm nhân viên</a></li></ul>',
    );
  }

}
/**
 * Implement get all staff
 */
function staff_get_staff_list(){
  $query = db_select('staff','st');
  $query->fields('st');
  $query->orderBy('name','ASC');
  $result = $query->execute()->fetchAll();
  $data = array();
  $data[''] = t('Không có nhân viên');
  if($result){
    foreach($result as $staff){
      $data[$staff->id] = $staff->name;
    }
  }
  return $data;
}